name: Appium CI
# on push we will trigger our code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # the machine type
    
    steps:
    - uses: actions/checkout@v2 #checkout the code 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: run tests on pCloudy   
      env:
          pCloudy_USERNAME: ${{ secrets.pCloudy_USERNAME }}
          pCloudy_ACCESS_KEY: ${{ secrets.pCloudy_ACCESS_KEY }} 
      run: mvn test
