name: Appium CI
# on push we will trigger our code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # the machine type   
    steps:
    - uses: actions/checkout@v2 #checkout the code 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests on BROWSERSTACK   
      env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }} 
      run: mvn clean test
